// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package com.nicoletfear.Robot2015.subsystems;

import com.nicoletfear.Robot2015.Robot;
import com.nicoletfear.Robot2015.RobotMap;
import com.nicoletfear.Robot2015.Subsystems;
import com.nicoletfear.Robot2015.commands.*;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class dog extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    DigitalInput limitSwitchTop = RobotMap.dogLimitSwitchTop;
    DigitalInput limitSwitchBottom = RobotMap.dogLimitSwitchBottom;
    //public static SpeedController dogMotor = new CANTalon(Subsystems.rioCheck.getPortNumber(RobotMap.TalonPortDog));
    //remove above
    public static SpeedController dogMotorRight = new CANTalon(Subsystems.rioCheck.getPortNumber(RobotMap.TalonPortDogRight));
    public static SpeedController dogMotorLeft = new CANTalon(Subsystems.rioCheck.getPortNumber(RobotMap.TalonPortDogLeft));
    // SpeedController motor = dogMotor;
    CANTalon talonTwo = new CANTalon(RobotMap.TalonIDDogRight);
    CANTalon talonThirteen = new CANTalon(RobotMap.TalonIDDogLeft);
    
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    public void startMotorTest(){
    	//dogMotor.set(0.5);
    	dogMotorRight.set(0.5);
    	dogMotorLeft.set(0.5);
    }
    public void stopMotorTest(){
    	//dogMotor.set(0);
    	dogMotorRight.set(0);
    	dogMotorLeft.set(0);
    }
    public void upMotorTest(){
    	//dogMotor.set(-0.5);
    	dogMotorRight.set(-0.5);
    	dogMotorLeft.set(-0.5);
    }
    public void downMotorTest(){
    	//dogMotor.set(0.5);
    	dogMotorRight.set(0.5);
    	dogMotorLeft.set(0.5);
    }
    public boolean upLimitPressed(){
    	if(RobotMap.dogLimitSwitchTop.get())
    	{
    		return false;
    	}
    	else{
		return true;
    	}
    }
    
    public boolean downLimitPressed(){
    	return !RobotMap.dogLimitSwitchBottom.get();
    }
}

